# Generated by Django 3.2.5 on 2021-07-19 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_law_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='law',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='main.lawcategory'),
        ),
    ]
